# Generated by Django 2.2.2 on 2019-06-18 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(help_text='This is what you will see on the front of the card.', verbose_name='Card prompt')),
                ('answer', models.TextField(help_text='This is what you will see on the back of the card.', verbose_name='Card answer')),
                ('stack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Stack')),
            ],
        ),
    ]
